### ISSUE TITLE
Is it necessary to create the "fcitx" and other directories under the "xdg-config" directory on the host machine?

### ISSUE THREAD

**Issue by ghost** [flathub/org.fcitx.Fcitx5#16]
![image](https://github.com/flathub/org.fcitx.Fcitx5/assets/64319186/834b6d5e-28ee-425c-b509-2efe4b41c486)

I saw this from flatpak document. So i'm thinking why don't we just use portals.

Then i  tried building the org.fcitx5.Fcitx5 (5.1.0pr branch) without following finish-args:
```yaml
  - --filesystem=xdg-config/kxkbrc:rw
  - --filesystem=xdg-config/fcitx:create
  - --filesystem=xdg-config/ibus:create
  - --filesystem=xdg-cache/ibus:create
``` 

It succeed and I have installed it and conducted some very limited tests. I found that the built Fcitx5 can run preliminarily smoothly (**NOTE: I only performed very rudimentary building and limited testing**), and the configuration files are managed in the `/home/user/.var/app/org.fcitx.Fcitx5/config` folder.

By the way now we should have these in the finish-args
```
  - --socket=wayland
  - --socket=fallback-x11
```
rather than 
```
  - --socket=x11
  - --socket=wayland
```

I'm still a beginner, so please don't get upset if you find my questions to be silly. Thank you.

**Comment by ghost** [comment]
I checked fcitx5-gtk module source code and found this 
```c++
ClassicUIConfig::ClassicUIConfig() {
    UniqueCPtr<char, g_free> filename(g_build_filename(
        g_get_user_config_dir(), "fcitx5/conf/classicui.conf", nullptr));
    GObjectUniquePtr<GFile> file(g_file_new_for_path(filename.get()));
    monitor_.reset(
        g_file_monitor_file(file.get(), G_FILE_MONITOR_NONE, nullptr, nullptr));

    g_signal_connect(monitor_.get(), "changed",
                     G_CALLBACK(&ClassicUIConfig::configChangedCallback), this);

    load();
}
```
This function calls `g_get_user_config_dir()`. So it's because the modules need the xdg-config/fcitx  directory to work i guees.

**Comment by wengxt** [comment]
@asuka909 the thing is complex.
1. as for X11, fcitx5 needs to talk to both wayland and X11 to be able to work  with native wayland and Xwayland under a regular wayland setup.
2. as for the files
xdg-config/fcitx5 xdg-data/fcitx5 are not necessary. The client side input panel (im module render the UI, which is a temp workaround for certain wayland setup) may read UI files, but it should work if it can't. We indeed intend to remove those.

xdg-config/fcitx (which is fcitx4), is necessary to support legacy fcitx4 im module. Such case could happen if user uses a old close-source proprietary app that bundles an old im module.

xdg-config/ibus xdg-cache/ibus are used to simulate ibus, which is necessary for GNOME3+ , whose compositor mutter directly talks to ibus via libibus.
