### ISSUE TITLE
Status and future of this app?

### ISSUE THREAD

**Issue by tinywrkb** [flathub/org.fcitx.Fcitx5#3]
Since its introduction, this packaging didn't receive any update, and the number of extensions is still limited.  

We need to update the packaging, but it's not that simple.  
I believe that the main problem that we're facing is the ABI dependency between extensions to app-packaged libs, which require being able to sync published builds of app and its extension, [something that is not possible when we have dedicated extension GitHub repositories](https://github.com/flathub/flathub/issues/2533).

The way I see it, there are two approaches to solve this.

#### Method1: Bundled extensions

The approach builds everything with the app, and then let flatpak-builder automatically create extensions, and remove them from the packaged app.  
This is the easy solution, but not without faults.  
It creates a Godzilla packaging, each build run will be pretty long. 
From personal experience, as someone who maintains such complex Flatpak packaging, I can tell that it's not fun and time-consuming. It doesn't help that Flathub's build servers do not use cached build artifacts or ccache.  

I started working on this, and I don't mind sending a PR, but I would prefer to go with method 2.

#### Method2: Directly push into Flathub

With this approach, the developer builds the app and extensions into a private Flatpak repo, and from there the developer can push all the Flatpak commits / ostree refs directly into Flathub.  
Currently, I know that Mozilla and OBS are allowed to push into Flathub, and the Element app is next.  
That's probably the best solution.

**Comment by tinywrkb** [comment]
> I started working on this, and I don't mind sending a PR, but I would prefer to go with method 2.

[Here's my WIP branch](https://github.com/tinywrkb/org.fcitx.Fcitx5/tree/bundled_extensions).

**Comment by wengxt** [comment]
The thing is we have a centralize repo for all flaptak, but flathub we need to manage it in different repos. My plan was to create a script to synchronize the changes from https://github.com/fcitx/flatpak-fcitx5/ to all the flathub repos. Just never got time to do that. Right now the idea is to use go-yq to patch the yaml and use github cli to create PR automatically and pull the tags.

**Comment by tinywrkb** [comment]
> The thing is we have a centralize repo for all flaptak, but flathub we need to manage it in different repos.

If there's already automation in place for updating the Fcitx Flatpak repo, then just also push directly to Flathub with [flatpak-manager](https://github.com/flatpak/flat-manager) when updating the Fcitx Flatpak repo, instead of having flathub-bot building from the `github.com/flathub/` repos.  
You'll need to request an access token from Flathub admins.

**Comment by wengxt** [comment]
Having the build on flathub can make it building on more architecture (e.g. arm)

**Comment by tinywrkb** [comment]
Nowadays, flathubbot only has aarch64 and x86_64 in its default architectures, and building for aarch64 is not that hard, just add `--arch=aarch64` to the flatpak-builer command and set the appropriate qmeu-user configs. See examples [here](https://github.com/flatpak/flatpak-docs/issues/620).

**Comment by tinywrkb** [comment]
> My plan was to create a script to synchronize the changes from https://github.com/fcitx/flatpak-fcitx5/ to all the flathub repos. 

Synchronizing changes of Flatpak manifests won't solve the problem with ABI breakage when Flatpak manifests of app and extension are updated at the same time, and then extensions are built by the CI against the publically published app version, instead of the updated unpublished version.

> Right now the idea is to use go-yq to patch the yaml and use github cli to create PR automatically and pull the tags.

In my [bundled_extensions](https://github.com/tinywrkb/org.fcitx.Fcitx5/tree/bundled_extensions) branch, I have f-e-d-c properties for pretty much everything except of `libkkc-data`, so updating is pretty easy, just run f-e-d-c on the app manifest.  
It also uses archive tarball sources for everything, so no need for network if tarballs are already cached.  
The only changes I want to make are fetching all of Fcitx5 tarballs from `download.fcitx-im.org`, and using this source also for the f-e-d-c checks with the HTML checker instead of Anitya.  
When I think it's ready, I will send a PR here to test it with flathubbot.

**Comment by tinywrkb** [comment]
Closing this as answer was received from the developer, the app is now finally updated, and another extension was added (Rime).  
I'm still concerned that having extensions built against a published application leaves the door open for a possible ABI breakage, when a user downloads an updated application build, but updated extensions are not available.  

I think that the best course of action would be to build locally and push everything (app+extensions) directly to Flathub.  
As it seems like my other suggestion, the bundled extensions method, was not adopted, I'm also closing the relevant PR.
